### PR TITLE
Support Rails 8.0

### PR DESCRIPTION
**Pull request by y-yagi**
Rails 8.0.0 has been released. This PR allows to use `rspec-activerecord-expectations` with Rails 8.0.0. Also, added the CI setting for that.

### CODE REVIEW

**Comment by y-yagi** [comment]
Hmm. It seems that CI hasn't worked.
https://github.com/jmmastey/rspec-activerecord-expectations/actions/runs/9616522997

**Comment by Alexander-Senko** [comment]
> Hmm. It seems that CI hasn't worked. https://github.com/jmmastey/rspec-activerecord-expectations/actions/runs/9616522997

It’s a 5 month old one. This PR needs an approval to run the CI, IMO.

**Comment by y-yagi** [comment]
> It’s a 5 month old one. This PR needs an approval to run the CI, IMO.

I mean CI has not worked at all since that time(at least). 
I already tried my PR on my fork, but I got the same error with the above.
https://github.com/y-yagi/rspec-activerecord-expectations/actions/runs/11792815198/job/32847126327

**Comment by Alexander-Senko** [comment]
> I mean CI has not worked at all since that time(at least).

Yes, the CI here looks broken, but it’s another story… It didn’t block [the PR for Rails 7](https://github.com/jmmastey/rspec-activerecord-expectations/pull/1) at least.

>  I already tried my PR on my fork, but I got the same error with the above.

And I suppose the tests to have passed locally. Maybe, this PR could pass then while the CI is being fixed separately?

**Comment by jmmastey** [comment]
Hello! Thanks, and I don't think it's a problem. I'll look at CI separately. Thanks for the contribution y'all.

**Review by jmmastey — APPROVED** [review]

**Comment by jmmastey** [comment]
Pushed as v3.1.0

**Comment by y-yagi** [comment]
@jmmastey Thanks!

**Pull request merged**
